// mediasfu_reactjs/src/components/Modal.tsx
import React from "react";
import { FaTimes } from "react-icons/fa";
import "../styles/SpaceDetails.css"; 

const Modal: React.FC<{
  isOpen: boolean;
  onClose: () => void;
  title: string;
  children: React.ReactNode;
}> = ({ isOpen, onClose, title, children }) => {
  if (!isOpen) return null;
  return (
    <div className="modal-overlay" onClick={onClose}>
      <div
        className="modal-content"
        onClick={(e) => e.stopPropagation()} 
      >
        <div className="modal-header">
          <h3>{title}</h3>
          <button className="modal-close-btn" onClick={onClose}>
            <FaTimes />
          </button>
        </div>
        <div className="modal-body">{children}</div>
        <div className="modal-footer">
          <button className="cancel-btn" onClick={onClose}>
            Close
          </button>
        </div>
      </div>
    </div>
  );
};

export default Modal;

// mediasfu_angular/src/app/components/modal-components/modal.component.ts
import { Component, Input, Output, EventEmitter } from '@angular/core';
import { CommonModule } from '@angular/common';
import { faTimes } from '@fortawesome/free-solid-svg-icons';
import { FontAwesomeModule } from '@fortawesome/angular-fontawesome';


@Component({
  selector: 'app-modal',
  templateUrl: './modal.component.html',
  styleUrls: ['./modal.component.css'],
  imports: [CommonModule, FontAwesomeModule]
})
export class ModalComponent {
  @Input() isOpen = false;
  @Input() title = '';
  @Output() onClose = new EventEmitter<void>();

  // Font Awesome Icons
  faTimes = faTimes;

  closeModal(event: MouseEvent): void {
    event.stopPropagation();
    this.onClose.emit();
  }

  stopPropagation(event: MouseEvent): void {
    event.stopPropagation();
  }
}

<div *ngIf="isOpen" class="modal-overlay" (click)="closeModal($event)">
  <div class="modal-content" (click)="stopPropagation($event)">
    <div class="modal-header">
      <h3>{{ title }}</h3>
      <button class="modal-close-btn" (click)="closeModal($event)">
        <fa-icon [icon]="faTimes"></fa-icon>
      </button>
    </div>
    <div class="modal-body">
      <ng-content></ng-content>
    </div>
    <div class="modal-footer">
      <button class="cancel-btn" (click)="closeModal($event)">Close</button>
    </div>
  </div>
</div>
