// mediasfu_angular/src/app/components/create-space-components/create-space.component.ts
import { Component, OnInit } from '@angular/core';
import { Router } from '@angular/router';
import { ApiService } from '../../api/api.service';
import { FontAwesomeModule } from '@fortawesome/angular-fontawesome';
import { CommonModule } from '@angular/common';
import { FormsModule } from '@angular/forms';
import { faArrowLeft } from '@fortawesome/free-solid-svg-icons';

@Component({
  selector: 'app-create-space',
  templateUrl: './create-space.component.html',
  styleUrls: ['./create-space.component.css'],
  providers: [ApiService],
  imports: [CommonModule, FormsModule, FontAwesomeModule]
})
export class CreateSpaceComponent implements OnInit {
  // Form fields
  title: string = '';
  description: string = '';
  capacity: number = 25;
  askToSpeak: boolean = false;
  askToJoin: boolean = false;
  startTime: string = '';
  duration: number = 15 * 60 * 1000; // Default duration in ms
  error: string = '';

  // Durations array matching React's generateDurations
  durations: { label: string; value: number }[] = [];

  // FontAwesome Icons
  faArrowLeft = faArrowLeft;

  constructor(private router: Router, private apiService: ApiService) {}

  ngOnInit(): void {
    this.durations = this.generateDurations();
  }

  /**
   * Generates durations similar to React's generateDurations function.
   */
  generateDurations(): { label: string; value: number }[] {
    const durations: { label: string; value: number }[] = [];
    const msPerMin = 60000;

    // 15 min to 180 min (3 hours) in 15-minute increments
    for (let m = 15; m <= 180; m += 15) {
      durations.push({ label: `${m} min`, value: m * msPerMin });
    }

    // 4 hr to 6 hr in 1-hour increments
    for (let h = 4; h <= 6; h++) {
      durations.push({ label: `${h} hr`, value: h * 60 * msPerMin });
    }

    return durations;
  }

  /**
   * Navigates back to the home page.
   */
  navigateBack(): void {
    this.router.navigate(['/']);
  }

  /**
   * Handles the creation of a new space.
   */
  async handleCreate(): Promise<void> {
    this.error = ''; // Reset error message

    const currentUserId = localStorage.getItem('currentUserId');
    if (!currentUserId) {
      this.router.navigate(['/welcome']);
      return;
    }

    const currentUser = await this.apiService.fetchUserById(currentUserId);
    if (!currentUser) {
      this.error = 'User not found.';
      return;
    }

    let startTimestamp = Date.now();
    if (this.startTime) {
      const chosenTime = new Date(this.startTime).getTime();
      const diff = chosenTime - Date.now();
      const threeDaysMs = 3 * 24 * 60 * 60 * 1000;

      // Validate start time: must be within the next 3 days and not in the past
      if (diff > threeDaysMs || diff < 0) {
        this.error = "Scheduled time must be within the next 3 days, and not in the past.";
        return;
      }
      startTimestamp = chosenTime;
    }

    // Validation: Title and Description length
    if (this.title.trim().length < 3) {
      this.error = "Title must be at least 3 characters";
      return;
    }
    if (this.description.trim().length < 10) {
      this.error = "Description must be at least 10 characters";
      return;
    }

    try {
      const newSpace = await this.apiService.createSpace(
        this.title.trim(),
        this.description.trim(),
        currentUser,
        {
          capacity: this.capacity,
          askToSpeak: this.askToSpeak,
          askToJoin: this.askToJoin,
          startTime: startTimestamp,
          duration: this.duration
        }
      );

      // Navigate to the newly created space's page
      this.router.navigate([`/space/${newSpace.id}`]);
    } catch (error: any) {
      console.error("Error creating space:", error);
      this.error = "Failed to create space. Please try again.";
    }
  }
}

<div class="create-space-container container">
  <div class="create-space-header">
    <button class="back-button" (click)="navigateBack()">
      <fa-icon [icon]="faArrowLeft"></fa-icon> Cancel
    </button>
    <h2>Create a New Space</h2>
  </div>

  <div class="form-container">
    <!-- Error Message -->
    <div *ngIf="error" class="error-message">
      {{ error }}
    </div>

    <!-- Title Field -->
    <div class="form-group">
      <label for="title">Title</label>
      <input
        id="title"
        type="text"
        [(ngModel)]="title"
        placeholder="e.g., Evening Discussion"
        required
      />
    </div>

    <!-- Description Field -->
    <div class="form-group">
      <label for="description">Description</label>
      <textarea
        id="description"
        [(ngModel)]="description"
        placeholder="Describe your space..."
        required
      ></textarea>
    </div>

    <!-- Capacity Field -->
    <div class="form-group">
      <label for="capacity">Capacity</label>
      <input
        id="capacity"
        type="number"
        [(ngModel)]="capacity"
        min="2"
        max="10000"
        required
      />
    </div>

    <!-- Ask to Speak Checkbox -->
    <div class="form-group checkbox-group">
      <label for="ask-to-speak">Ask to Speak</label>
      <input id="ask-to-speak" type="checkbox" [(ngModel)]="askToSpeak" />
    </div>

    <!-- Ask to Join Checkbox -->
    <div class="form-group checkbox-group">
      <label for="ask-to-join">Ask to Join</label>
      <input id="ask-to-join" type="checkbox" [(ngModel)]="askToJoin" />
    </div>

    <!-- Start Time Field -->
    <div class="form-group">
      <label for="start-time">Start Time (optional)</label>
      <input id="start-time" type="datetime-local" [(ngModel)]="startTime" />
      <small>
        Leave blank for immediate start. Must be within the next 3 days.
      </small>
    </div>

    <!-- Duration Field -->
    <div class="form-group">
      <label for="duration">Duration</label>
      <select id="duration" [(ngModel)]="duration" required>
        <option *ngFor="let d of durations" [value]="d.value">
          {{ d.label }}
        </option>
      </select>
      <small>
        Choose how long the space will run before automatically ending.
      </small>
    </div>

    <!-- Create Space Button -->
    <button class="create-space-button" (click)="handleCreate()">
      Create Space
    </button>
  </div>
</div>

// mediasfu_reactjs/src/components/CreateSpace.tsx
import React, { useState, useMemo } from "react";
import { createSpace, fetchUserById } from "../api";
import { useNavigate } from "react-router-dom";
import { FaArrowLeft } from "react-icons/fa";

function generateDurations(): { label: string; value: number }[] {
  const durations: { label: string; value: number }[] = [];
  const msPerMin = 60000;
  for (let m = 15; m <= 180; m += 15) {
    durations.push({ label: `${m} min`, value: m * msPerMin });
  }
  for (let h = 4; h <= 6; h++) {
    durations.push({ label: `${h} hr`, value: h * 60 * msPerMin });
  }
  return durations;
}

export const CreateSpace: React.FC = () => {
  const [title, setTitle] = useState("");
  const [description, setDescription] = useState("");
  const [capacity, setCapacity] = useState(25);
  const [askToSpeak, setAskToSpeak] = useState(false);
  const [askToJoin, setAskToJoin] = useState(false);
  const [startTime, setStartTime] = useState("");
  const [error, setError] = useState("");
  const [duration, setDuration] = useState<number>(15 * 60 * 1000);

  const navigate = useNavigate();
  const durations = useMemo(() => generateDurations(), []);

  async function handleCreate() {
    const currentUserId = localStorage.getItem("currentUserId");
    if (!currentUserId) {
      navigate("/welcome");
      return;
    }
    const currentUser = await fetchUserById(currentUserId);
    if (!currentUser) return;

    let startTimestamp = Date.now();
    if (startTime) {
      const chosenTime = new Date(startTime).getTime();
      const diff = chosenTime - Date.now();
      const threeDaysMs = 3 * 24 * 60 * 60 * 1000;
      if (diff > threeDaysMs || diff < 0) {
        setError(
          "Scheduled time must be within the next 3 days, and not in the past."
        );
        return;
      }
      startTimestamp = chosenTime;
    }

    // Validation
    if (title.length < 3) {
      setError("Title must be at least 3 characters");
      return;
    }
    if (description.length < 10) {
      setError("Description must be at least 10 characters");
      return;
    }

    const newSpace = await createSpace(title, description, currentUser, {
      capacity,
      askToSpeak,
      askToJoin,
      startTime: startTimestamp,
      duration,
    });
    navigate(`/space/${newSpace.id}`);
  }

  React.useEffect(() => {
    const timeout = setTimeout(() => setError(''), 3000);
    return () => clearTimeout(timeout);
  }, [error]);

  return (
    <div className="create-space-container container">
      <div className="create-space-header">
        <button className="back-button" onClick={() => navigate("/")}>
          <FaArrowLeft className="icon" /> Cancel
        </button>
        <h2>Create a New Space</h2>
      </div>
      <div className="form-container">
        {error && (
          <div style={{ color: "red", marginBottom: "1em" }}>{error}</div>
        )}

        <label>Title</label>
        <input
          value={title}
          onChange={(e) => setTitle(e.target.value)}
          placeholder="e.g., Evening Discussion"
        />

        <label>Description</label>
        <textarea
          value={description}
          onChange={(e) => setDescription(e.target.value)}
          placeholder="Describe your space..."
        ></textarea>

        <label>Capacity</label>
        <input
          type="number"
          value={capacity}
          min={2}
          max={10000}
          onChange={(e) => setCapacity(Number(e.target.value))}
        />

        <div className="checkbox-group">
          <label>Ask to Speak</label>
          <input
            type="checkbox"
            checked={askToSpeak}
            onChange={(e) => setAskToSpeak(e.target.checked)}
          />
        </div>
        <hr />

        <div className="checkbox-group">
          <label>Ask to Join</label>
          <input
            type="checkbox"
            checked={askToJoin}
            onChange={(e) => setAskToJoin(e.target.checked)}
          />
        </div>
        <hr />

        <div style={{ margin: "1em 0" }}>
          <label
            style={{ display: "block", marginBottom: "0.5em", fontWeight: 600 }}
          >
            Start Time (optional)
          </label>
          <input
            type="datetime-local"
            value={startTime}
            onChange={(e) => setStartTime(e.target.value)}
          />
          <small
            style={{ display: "block", color: "#555", marginTop: "0.5em" }}
          >
            Leave blank for immediate start. Must be within next 3 days.
          </small>
        </div>
        <hr />

        <div style={{ margin: "1em 0" }}>
          <label>Duration</label>
          <select
            value={duration}
            onChange={(e) => setDuration(Number(e.target.value))}
          >
            {durations.map((d) => (
              <option key={d.value} value={d.value}>
                {d.label}
              </option>
            ))}
          </select>
          <small
            style={{ display: "block", color: "#555", marginTop: "0.5em" }}
          >
            Choose how long the space will run before automatically ending.
          </small>
        </div>
        <hr />
        {error && (
          <div style={{ color: "red", marginBottom: "1em" }}>{error}</div>
        )}
        <button style={{ marginTop: "1em" }} onClick={handleCreate}>
          Create Space
        </button>
      </div>
    </div>
  );
};
