// mediasfu_angular/src/app/components/header-components/header.component.ts
import { Component, OnInit, OnDestroy } from '@angular/core';
import { Router, NavigationEnd } from '@angular/router';
import { BehaviorSubject, Subscription } from 'rxjs';
import { filter } from 'rxjs/operators';
import { ApiService } from '../../api/api.service';
import { UserProfile } from '../../../types';
import { FontAwesomeModule } from '@fortawesome/angular-fontawesome';
import { faSignOutAlt } from '@fortawesome/free-solid-svg-icons';
import { CommonModule } from '@angular/common';

@Component({
  selector: 'app-header',
  templateUrl: './header.component.html',
  styleUrls: ['./header.component.css'],
  imports: [FontAwesomeModule, CommonModule],
})
export class HeaderComponent implements OnInit, OnDestroy {
  currentUser = new BehaviorSubject<UserProfile | null>(null);
  faSignOutAlt = faSignOutAlt;
  private urlSubscription!: Subscription;

  constructor(public router: Router, private apiService: ApiService) {}

  ngOnInit(): void {
    this.checkCurrentUser();

    // Listen to URL changes
    this.urlSubscription = this.router.events
      .pipe(filter((event) => event instanceof NavigationEnd))
      .subscribe(() => {
        this.handleUrlChange();
      });
  }

  ngOnDestroy(): void {
    // Clean up subscription
    if (this.urlSubscription) {
      this.urlSubscription.unsubscribe();
    }
  }

  /**
   * Checks if a user is logged in and updates the header state.
   */
  private async checkCurrentUser(): Promise<void> {
    const currentUserId = localStorage.getItem('currentUserId');
    if (currentUserId) {
      const user = await this.apiService.fetchUserById(currentUserId);
      if (user) {
        this.currentUser.next({
          ...user,
          avatarUrl: user.avatarUrl || 'https://www.mediasfu.com/logo192.png',
        });
      }
    } else {
      this.currentUser.next(null); // Clear user if not logged in
    }
  }

  /**
   * Handles URL change events.
   */
  private handleUrlChange(): void {
    // Perform any actions needed on URL change
    this.checkCurrentUser(); // Example: Refresh user data if needed
  }

  /**
   * Handles user logout and navigates to the welcome page.
   */
  async handleLogout(): Promise<void> {
    const currentUserId = localStorage.getItem('currentUserId');
    if (currentUserId) {
      await this.apiService.freeUser(currentUserId);
      localStorage.removeItem('currentUserId');
      this.currentUser.next(null);
      localStorage.setItem('lastUserId', currentUserId || '');
      this.router.navigate(['/welcome']);
    }
  }
}

<header class="main-container">
  <!-- Title Section -->
  <div class="header-title" (click)="router.navigate(['/'])">SpacesTek</div>

  <div *ngIf="(currentUser | async) as user" class="header-user">
    <div class="user-info">
      <img [src]="user.avatarUrl" [alt]="user.displayName" class="user-avatar" />
      <span class="user-name">{{ user.displayName }}</span>
    </div>
    <button class="logout-button" (click)="handleLogout()">
      <fa-icon [icon]="faSignOutAlt"></fa-icon>
      Logout
    </button>
  </div>
</header>

// mediasfu_reactjs/src/components/Header.tsx
import React, { useEffect, useState } from "react";
import { useNavigate, useLocation } from "react-router-dom";
import { FaSignOutAlt } from "react-icons/fa";
import { freeUser, fetchUserById } from "../api";
import { UserProfile } from "../types";

export const Header: React.FC = () => {
  const navigate = useNavigate();
  const location = useLocation();
  const currentUserId = localStorage.getItem("currentUserId");
  const [currentUser, setCurrentUser] = useState<UserProfile | null>(null);

  useEffect(() => {
    if (currentUserId) {
      fetchUserById(currentUserId).then((user) => {
        if (user) {
          setCurrentUser({
            ...user,
            avatarUrl: user.avatarUrl || "https://www.mediasfu.com/logo192.png",
          });
        } else {
          localStorage.removeItem("currentUserId");
          navigate("/welcome");
        }
      });
    }
  }, [currentUserId, navigate]);

  function handleLogout() {
    if (currentUserId) {
      freeUser(currentUserId);
    }
    localStorage.setItem("lastUserId", currentUserId || "");
    localStorage.removeItem("currentUserId");
    navigate("/welcome");
  }

  return (
    <header
      className="main-container"
      style={{
        padding: "1em",
        display: "flex",
        justifyContent: "space-between",
        alignItems: "center",
        background: "#fff",
        borderBottom: "1px solid #eee",
        position: "sticky",
        top: 0,
        zIndex: 1000,
      }}
    >
      <div
        style={{
          fontWeight: "bold",
          fontSize: "1.2em",
          cursor: "pointer",
        }}
        onClick={() => navigate("/")}
      >
        SpacesTek
      </div>

      {currentUser && location.pathname !== "/welcome" && (
        <div style={{ display: "flex", alignItems: "center", gap: "1em" }}>
          {/* User Info */}
          <div style={{ display: "flex", alignItems: "center", gap: "0.5em" }}>
            <img
              src={currentUser.avatarUrl}
              alt={currentUser.displayName}
              style={{
                width: "40px",
                height: "40px",
                borderRadius: "50%",
                objectFit: "cover",
              }}
            />
            <span
              style={{ fontWeight: "600", fontSize: "0.9em", color: "#333" }}
            >
              {currentUser.displayName}
            </span>
          </div>

          {/* Logout Button */}
          <button
            style={{
              background: "transparent",
              color: "#1da1f2",
              border: "none",
              cursor: "pointer",
              display: "flex",
              alignItems: "center",
              fontSize: "0.9em",
            }}
            onClick={handleLogout}
          >
            <FaSignOutAlt style={{ marginRight: "0.3em" }} /> Logout
          </button>
        </div>
      )}
    </header>
  );
};
