// mediasfu_angular/src/app/components/spaces-list-components/spaces-list.component.ts
import { Component, OnInit, OnDestroy } from '@angular/core';
import { ApiService } from '../../api/api.service';
import { Space, UserProfile } from '../../../types';
import { BehaviorSubject, Subscription, interval } from 'rxjs';
import { Router } from '@angular/router';
import { FontAwesomeModule } from '@fortawesome/angular-fontawesome';
import {
  faSearch,
  faFilter,
  faChevronLeft,
  faChevronRight,
  faAngleDoubleLeft,
  faAngleDoubleRight,
  faList
} from '@fortawesome/free-solid-svg-icons';
import { FormsModule } from '@angular/forms';
import { CommonModule } from '@angular/common';
import { debounceTime } from 'rxjs/operators'

import { SidebarCardComponent } from '../side-bar-components/sidebar-card.component';
import { SpaceCardComponent } from '../space-card-components/space-card.component';

@Component({
  selector: 'app-spaces-list',
  templateUrl: './spaces-list.component.html',
  styleUrls: ['./spaces-list.component.css'],
  imports: [
    CommonModule,
    FontAwesomeModule,
    FormsModule,
    SidebarCardComponent,
    SpaceCardComponent
  ]
})
export class SpacesListComponent implements OnInit, OnDestroy {
  // FontAwesome Icons
   faSearch = faSearch;
   faFilter = faFilter;
   faChevronLeft = faChevronLeft;
   faChevronRight = faChevronRight;
   faAngleDoubleLeft = faAngleDoubleLeft;
   faAngleDoubleRight = faAngleDoubleRight;
   faList = faList;

  // State Management with BehaviorSubjects
  spaces = new BehaviorSubject<Space[]>([]);
  previousSpaces: Space[] = [];
  filteredSpaces = new BehaviorSubject<Space[]>([]);
  recentSpaces = new BehaviorSubject<Space[]>([]);
  topSpaces = new BehaviorSubject<Space[]>([]);
  user = new BehaviorSubject<UserProfile | null>(null);
  activeSpace = new BehaviorSubject<Space | null>(null);
  message = new BehaviorSubject<string | null>(null);
  pendingJoin = new BehaviorSubject<[string, string][]>([]);

  // Component Properties for Form Inputs
  searchQuery: string = "";
  filterStatus: string = "All";
  currentPage: number = 1;
  itemsPerPage: number = 5;

  // Subscriptions
  private intervalSub!: Subscription;
  private pendingJoinSub!: Subscription;
  private spacesSub!: Subscription;

  constructor(private apiService: ApiService, public router: Router) { }

  ngOnInit(): void {
    this.loadSpaces();
    this.intervalSub = interval(2000).subscribe(() => this.loadSpaces());

    this.pendingJoinSub = this.pendingJoin
      .pipe(debounceTime(300))
      .subscribe(() => this.checkPendingJoin());

    this.spacesSub = this.spaces
      .pipe(debounceTime(300))
      .subscribe(() => this.filterSpaces());
  }

  ngOnDestroy(): void {
    if (this.intervalSub) this.intervalSub.unsubscribe();
    if (this.pendingJoinSub) this.pendingJoinSub.unsubscribe();
    if (this.spacesSub) this.spacesSub.unsubscribe();
  }

  /**
   * Loads spaces from the API and updates state accordingly.
   */
  async loadSpaces(): Promise<void> {
    try {
      const allSpaces = await this.apiService.fetchSpaces();
      const processedSpaces = allSpaces.map(space => ({
        ...space,
        participants: space.participants.map(p => ({
          ...p,
          avatarUrl: p.avatarUrl || "https://www.mediasfu.com/logo192.png",
        })),
      }));
      // Only update if data has changed
      if (JSON.stringify(this.previousSpaces) !== JSON.stringify(processedSpaces)) {
        this.previousSpaces = processedSpaces;
        this.spaces.next(processedSpaces);
        this.calculateTopAndRecentSpaces(processedSpaces);
        this.updateUserAndActiveSpace(processedSpaces);
      }

    } catch (error) {
      console.error("Error loading spaces:", error);
      this.message.next("Failed to load spaces. Please try again later.");
      setTimeout(() => this.message.next(null), 2000);
    }
  }

  /**
   * Calculates the top and recent spaces for the user.
   * @param spaces The list of spaces to evaluate.
   */
  private calculateTopAndRecentSpaces(spaces: Space[]): void {
    const userId = localStorage.getItem('currentUserId');
    if (!userId) return;

    const userRecentSpaces = spaces.filter(
      (space) =>
        space.participants.some((p) => p.id === userId) ||
        (space.approvedToJoin && space.approvedToJoin.includes(userId))
    );
    const sortedTopSpaces = [...spaces].sort(
      (a, b) => b.participants.length - a.participants.length
    );

    this.recentSpaces.next(userRecentSpaces.slice(0, 5));
    this.topSpaces.next(sortedTopSpaces.slice(0, 5));
  }

  /**
   * Updates the user and active space based on the list of spaces.
   * @param spaces The list of spaces to evaluate.
   */
  private async updateUserAndActiveSpace(spaces: Space[]): Promise<void> {
    const userId = localStorage.getItem('currentUserId');
    if (!userId) return;

    const spaceUser = await this.apiService.fetchUserById(userId);
    this.user.next(spaceUser!);

    const active = spaces.find(
      (space) =>
        space.active &&
        !space.endedAt &&
        space.participants.some((p) => p.id === userId)
    );
    this.activeSpace.next(active || null);
  }

  /**
   * Filters spaces based on search query and filter status.
   */
  filterSpaces(): void {
    const query = this.searchQuery.toLowerCase();
    const status = this.filterStatus;

    let filtered = this.spaces.value.filter(space =>
      space.title.toLowerCase().includes(query) ||
      space.description.toLowerCase().includes(query)
    );

    if (status !== "All") {
      filtered = filtered.filter(space => {
        const now = Date.now();
        const ended = this.isSpaceEnded(space);
        const scheduled = this.isSpaceScheduled(space);
        const live = space.active && !ended && !scheduled;

        switch (status) {
          case "Live":
            return live;
          case "Scheduled":
            return scheduled;
          case "Ended":
            return ended;
          default:
            return true;
        }
      });
    }

    this.currentPage = 1; // Reset to first page on filter
    this.filteredSpaces.next(filtered);
  }

  /**
   * Checks pendingJoin to see if user has been approved.
   */
  checkPendingJoin(): void {
    if (this.pendingJoin.value.length === 0) return;

    const [spaceId, userId] = this.pendingJoin.value[this.pendingJoin.value.length - 1];
    const space = this.spaces.value.find(s => s.id === spaceId);
    if (!space) return;

    if (space.approvedToJoin && space.approvedToJoin.includes(userId)) {
      this.message.next(`You have been approved to join the space: ${space.title}`);
      setTimeout(() => this.message.next(null), 2000);
      // Remove from pending join
      this.pendingJoin.next(this.pendingJoin.value.slice(0, -1));
    }
  }

  /**
   * Determines if a space can be joined now.
   * @param space The space to evaluate.
   */
  getCanJoinNow(space: Space): boolean {
    const diff = space.startedAt - Date.now();
    const fiveMinutes = 5 * 60 * 1000;
    const ended = this.isSpaceEnded(space);
    return diff <= fiveMinutes && !ended;
  }

  /**
   * Determines if a space has ended.
   * @param space The space to evaluate.
   */
  isSpaceEnded(space: Space): boolean {
    return !!space.endedAt && !space.active;
  }

  /**
   * Determines if a space is scheduled.
   * @param space The space to evaluate.
   */
  isSpaceScheduled(space: Space): boolean {
    return Date.now() < space.startedAt;
  }

  /**
   * Counts the number of participants in a space.
   * @param space The space to evaluate.
   */
  participantCount(space: Space): number {
    return space.participants.length;
  }

  /**
   * Determines the join status of the user for a space.
   * @param space The space to evaluate.
   * @param userId The user's ID.
   */
  getJoinStatus(space: Space, userId: string | null): string | null {
    if (!userId) return null;
    if (space.banned && space.banned.includes(userId)) return "Banned";
    if (space.participants.some(p => p.id === userId)) return "Approved";
    if (space.approvedToJoin && space.approvedToJoin.includes(userId)) return "Lobby";
    if (space.askToJoinQueue.includes(userId)) return "Pending approval";
    if (space.askToJoinHistory.includes(userId)) return "Rejected";
    if (!space.askToJoin) return "Lobby";
    if (space.askToJoin && !space.participants.some(p => p.id === userId))
      return "Request to join";
    return "Approved";
  }

  /**
   * Handles joining a space.
   * @param space The space to join.
   */
  async handleJoinSpace(space: Space): Promise<void> {
    const userId = localStorage.getItem("currentUserId");
    if (!userId || !this.user.value) {
      this.router.navigate(['/welcome']);
      return;
    }

    try {
      await this.apiService.joinSpace(space.id, this.user.value, !space.askToSpeak);
      this.router.navigate([`/space/${space.id}`]);
    } catch (error) {
      console.error("Error joining space:", error);
      this.message.next("Failed to join space. Please try again.");
      setTimeout(() => this.message.next(null), 2000);
    }
  }

  /**
   * Handles requesting to join a space.
   * @param space The space to request joining.
   */
  async handleRequestJoinSpace(space: Space): Promise<void> {
    const userId = localStorage.getItem("currentUserId");
    if (!userId || !this.user.value) {
      this.router.navigate(['/welcome']);
      return;
    }

    try {
      await this.apiService.joinSpace(space.id, this.user.value, !space.askToSpeak);
      this.pendingJoin.next([...this.pendingJoin.value, [space.id, this.user.value.id]]);
      this.message.next("Your request to join has been sent.");
      setTimeout(() => this.message.next(null), 2000);
    } catch (error) {
      console.error("Error requesting to join space:", error);
      this.message.next("Failed to request to join space. Please try again.");
      setTimeout(() => this.message.next(null), 2000);
    }
  }

  /**
   * Navigates to the space details page.
   * @param spaceId The ID of the space.
   */
  navigateToSpace(spaceId: string): void {
    this.router.navigate([`/space/${spaceId}`]);
  }

  /**
   * Handles changes in search query and filter status.
   */
  onSearchQueryChange(event: Event): void {
    try {
      const query = (event.target as HTMLInputElement).value;
      this.searchQuery = query;
      this.filterSpaces();
    } catch (error) {
    }
  }

  onFilterStatusChange(event: Event): void {
    try {
      const status = (event.target as HTMLSelectElement).value;
      this.filterStatus = status;
      this.filterSpaces();
    } catch (error) {
    }
  }

  /**
   * Pagination handlers
   */
  handleFirstPage(): void {
    this.currentPage = 1;
  }

  handleLastPage(): void {
    this.currentPage = this.getTotalPages();
  }

  handlePrevPage(): void {
    const prev = this.currentPage > 1 ? this.currentPage - 1 : this.currentPage;
    this.currentPage = prev;
  }

  handleNextPage(): void {
    const next = this.currentPage < this.getTotalPages() ? this.currentPage + 1 : this.currentPage;
    this.currentPage = next;
  }

  handleItemsPerPageChange(event: Event): void {
    const value = parseInt((event.target as HTMLSelectElement).value);
    this.itemsPerPage = value;
    this.currentPage = 1; // Reset to first page
  }

  /**
   * Retrieves the current spaces to display based on pagination.
   */
  getCurrentSpaces(): Space[] {
    const start = (this.currentPage - 1) * this.itemsPerPage;
    const end = start + this.itemsPerPage;
    return this.filteredSpaces.value.slice(start, end);
  }

  /**
   * Retrieves the total number of pages based on the filtered spaces and items per page.
   */
  getTotalPages(): number {
    return Math.ceil(this.filteredSpaces.value.length / this.itemsPerPage);
  }
}

<div class="spaces-list-layout">

  <!-- Left Sidebar - Top Spaces -->
  <div class="left-sidebar">
    <h3>Top Spaces</h3>
    <div class="sidebar-card-container">
      <app-sidebar-card
        *ngFor="let space of topSpaces.value"
        [space]="space"
        (navigateToSpace)="navigateToSpace(space.id)">
      </app-sidebar-card>
    </div>
  </div>

  <!-- Main Content -->
  <div class="spaces-list-container container">
    <!-- Message -->
    <div *ngIf="message.value" class="error-message">
      {{ message.value }}
    </div>
    <h1>Browse Spaces</h1>

    <!-- Search and Filter Bar -->
    <div class="search-filter-bar">
      <!-- Search Bar -->
      <div class="search-bar">
        <input
          type="text"
          placeholder="Search for spaces..."
          [(ngModel)]="searchQuery"
          (ngModelChange)="onSearchQueryChange($event)"
        />
        <fa-icon [icon]="faSearch" class="search-icon"></fa-icon>
      </div>

      <!-- Filter Dropdown -->
      <div class="filter-dropdown">
        <fa-icon [icon]="faFilter" class="filter-icon"></fa-icon>
        <select
          [(ngModel)]="filterStatus"
          (change)="onFilterStatusChange($event)"
        >
          <option value="All">All</option>
          <option value="Live">Live</option>
          <option value="Scheduled">Scheduled</option>
          <option value="Ended">Ended</option>
        </select>
      </div>
    </div>

    <!-- Create Space Button -->
    <button
      class="create-space-button"
      (click)="router.navigate(['/create-space'])"
    >
      Create New Space
    </button>

    <!-- Spaces List -->
    <ul class="spaces-list">
      <app-space-card
      *ngFor="let space of getCurrentSpaces()"
      [space]="space"
      [userId]="user.value?.id!"
      (joinSpaceEvent)="handleJoinSpace($event)"
      (requestJoinSpaceEvent)="handleRequestJoinSpace($event)"
      (viewDetailsEvent)="navigateToSpace($event.id)"
    ></app-space-card>
    </ul>

    <!-- Pagination Controls -->
    <div *ngIf="getTotalPages() > 1" class="pagination-controls">
      <!-- Items Per Page -->
      <div class="items-per-page">
        <fa-icon [icon]="faList" class="pagination-icon"></fa-icon>
        <label for="itemsPerPage">Show:</label>
        <select
          id="itemsPerPage"
          [(ngModel)]="itemsPerPage"
          (change)="handleItemsPerPageChange($event)"
        >
          <option [value]="5">5</option>
          <option [value]="10">10</option>
          <option [value]="25">25</option>
          <option [value]="50">50</option>
        </select>
      </div>

      <!-- Page Navigation -->
      <div class="page-navigation">
        <button
          (click)="handleFirstPage()"
          [disabled]="currentPage === 1"
          title="First Page"
          aria-label="First Page"
        >
          <fa-icon [icon]="faAngleDoubleLeft"></fa-icon>
        </button>
        <button
          (click)="handlePrevPage()"
          [disabled]="currentPage === 1"
          title="Previous Page"
          aria-label="Previous Page"
        >
          <fa-icon [icon]="faChevronLeft"></fa-icon>
        </button>
        <span class="current-page">
          Page {{ currentPage }} of {{ getTotalPages() }}
        </span>
        <button
          (click)="handleNextPage()"
          [disabled]="currentPage === getTotalPages()"
          title="Next Page"
          aria-label="Next Page"
        >
          <fa-icon [icon]="faChevronRight"></fa-icon>
        </button>
        <button
          (click)="handleLastPage()"
          [disabled]="currentPage === getTotalPages()"
          title="Last Page"
          aria-label="Last Page"
        >
          <fa-icon [icon]="faAngleDoubleRight"></fa-icon>
        </button>
      </div>
    </div>
  </div>

  <!-- Right Sidebar - Recent Spaces -->
  <div class="right-sidebar">
    <h3>Recent Spaces</h3>
    <div class="sidebar-card-container">
      <app-sidebar-card
        *ngFor="let space of recentSpaces.value"
        [space]="space"
        (navigateToSpace)="navigateToSpace(space.id)">
      </app-sidebar-card>
    </div>
  </div>
</div>

// mediasfu_reactjs/src/components/SpacesList.tsx
import React, { useEffect, useState } from "react";
import { fetchUserById, fetchSpaces, joinSpace } from "../api";
import { Space, UserProfile } from "../types";
import { useNavigate } from "react-router-dom";
import {
  FaUsers,
  FaClock,
  FaCheckCircle,
  FaFlagCheckered,
  FaSearch,
  FaFilter,
  FaChevronLeft,
  FaChevronRight,
  FaAngleDoubleLeft,
  FaAngleDoubleRight,
  FaList,
} from "react-icons/fa";
import "../styles/SpacesList.css";

export const SpacesList: React.FC = () => {
  const [spaces, setSpaces] = useState<Space[]>([]);
  const [filteredSpaces, setFilteredSpaces] = useState<Space[]>([]);
  const [searchQuery, setSearchQuery] = useState("");
  const [filterStatus, setFilterStatus] = useState<string>("All");
  const [recentSpaces, setRecentSpaces] = useState<Space[]>([]);
  const [topSpaces, setTopSpaces] = useState<Space[]>([]);
  const [user, setUser] = useState<UserProfile | null>(null);
  const [currentPage, setCurrentPage] = useState<number>(1);
  const [itemsPerPage, setItemsPerPage] = useState<number>(5);
  const [pendingJoin, setPendingJoin] = useState<[string, string][]>([]);
  const [message, setMessage] = useState<string | null>(null);
  const [activeSpace, setActiveSpace] = useState<Space | null>(null); // manage this for playing media in an active space
  const navigate = useNavigate();

  async function loadSpaces() {
    const allSpaces = await fetchSpaces();
    setSpaces(
      allSpaces.map((space) => ({
        ...space,
        participants: space.participants.map((p) => ({
          ...p,
          avatarUrl: p.avatarUrl || "https://www.mediasfu.com/logo192.png",
        })),
      }))
    );

    // Calculate recent and top spaces
    const userId = localStorage.getItem("currentUserId");
    if (!userId) return;

    const userRecentSpaces = allSpaces.filter(
      (space) =>
        space.participants.some((p) => p.id === userId) ||
        space.approvedToJoin?.includes(userId)
    );
    const sortedTopSpaces = [...allSpaces].sort(
      (a, b) => b.participants.length - a.participants.length
    );

    setRecentSpaces(userRecentSpaces.slice(0, 5));
    setTopSpaces(sortedTopSpaces.slice(0, 5));

    const spaceUser = await fetchUserById(userId);
    setUser(spaceUser!);

    // Check if user is in an active space
    const active = allSpaces.find(
      (space) =>
        space.active &&
        !space.endedAt &&
        space.participants.some((p) => p.id === userId)
    );

    setActiveSpace(active || null);
  }

  useEffect(() => {
    loadSpaces();
    const interval = setInterval(loadSpaces, 2000); // Refresh every 5 seconds
    return () => clearInterval(interval);
    // eslint-disable-next-line react-hooks/exhaustive-deps
  }, []);

  useEffect(() => {
    // Filter spaces based on search query and filter status
    let filtered = spaces.filter(
      (space) =>
        space.title.toLowerCase().includes(searchQuery.toLowerCase()) ||
        space.description.toLowerCase().includes(searchQuery.toLowerCase())
    );

    if (filterStatus !== "All") {
      filtered = filtered.filter((space) => {
        const now = Date.now();
        const ended = !!space.endedAt && !space.active;
        const scheduled = now < space.startedAt;
        const live = space.active && !ended && !scheduled;

        switch (filterStatus) {
          case "Live":
            return live;
          case "Scheduled":
            return scheduled;
          case "Ended":
            return ended;
          default:
            return true;
        }
      });
    }

    setFilteredSpaces(filtered);
  }, [searchQuery, filterStatus, spaces]);

  useEffect(() => {
    setCurrentPage(1);
  }, [filterStatus]);

  // listen to pendingJoin changes and see if user has been approved
  useEffect(() => {
    if (pendingJoin.length === 0) return;

    const [spaceId, userId] = pendingJoin[pendingJoin.length - 1];
    const space = spaces.find((s) => s.id === spaceId);
    if (!space) return;

    if (space.approvedToJoin?.includes(userId)) {
      setMessage(`You have been approved to join the space: ${space.title}`);
      setTimeout(() => setMessage(null), 5000);
      // Remove from pending join
      setPendingJoin((prev) => prev.slice(0, -1));
    }
  }, [pendingJoin, spaces]);

  function isSpaceEnded(space: Space): boolean {
    return !!space.endedAt && !space.active;
  }

  function isSpaceScheduled(space: Space): boolean {
    return Date.now() < space.startedAt;
  }

  function participantCount(space: Space): number {
    return space.participants.length;
  }

  function getJoinStatus(space: Space, userId: string | null): string | null {
    if (!userId) return null;
    if (space.banned?.includes(userId)) return "Banned";
    if (space.participants.some((p) => p.id === userId)) return "Approved";
    if (space.approvedToJoin!.includes(userId)) return "Lobby";
    if (space.askToJoinQueue.includes(userId)) return "Pending approval";
    if (space.askToJoinHistory.includes(userId)) return "Rejected";
    if (!space.askToJoin) return "Lobby";
    if (space.askToJoin && !space.participants.some((p) => p.id === userId))
      return "Request to join";
    return "Approved";
  }

  // Pagination calculations
  const totalItems = filteredSpaces.length;
  const totalPages = Math.ceil(totalItems / itemsPerPage);
  const indexOfLastSpace = currentPage * itemsPerPage;
  const indexOfFirstSpace = indexOfLastSpace - itemsPerPage;
  const currentSpaces = filteredSpaces.slice(
    indexOfFirstSpace,
    indexOfLastSpace
  );

  // Handlers for pagination
  const handleFirstPage = () => setCurrentPage(1);
  const handleLastPage = () => setCurrentPage(totalPages);
  const handlePrevPage = () =>
    setCurrentPage((prev) => (prev > 1 ? prev - 1 : prev));
  const handleNextPage = () =>
    setCurrentPage((prev) => (prev < totalPages ? prev + 1 : prev));
  const handleItemsPerPageChange = (
    e: React.ChangeEvent<HTMLSelectElement>
  ) => {
    setItemsPerPage(Number(e.target.value));
    setCurrentPage(1);
  };

  return (
    <div className="spaces-list-layout">
      {/* Left Sidebar - Top Spaces */}
      <div className="left-sidebar">
        <h3>Top Spaces</h3>
        <div className="sidebar-card-container">
          {topSpaces.map((space) => (
            <div
              key={space.id}
              className="sidebar-card"
              onClick={() => navigate(`/space/${space.id}`)}
            >
              <h4 className="sidebar-card-title">{space.title}</h4>
              <p className="sidebar-card-participants">
                <FaUsers /> {participantCount(space)} participants
              </p>
              <p className="sidebar-card-status">
                {isSpaceEnded(space)
                  ? "Ended"
                  : isSpaceScheduled(space)
                  ? "Scheduled"
                  : "Live"}
              </p>
            </div>
          ))}
        </div>
      </div>

      {/* Main Content */}
      <div className="spaces-list-container container">
        {message && <div className="error-message">{message}</div>}
        <h1>Browse Spaces</h1>

        {/* Search and Filter Bar */}
        <div className="search-filter-bar">
          {/* Search Bar */}
          <div className="search-bar">
            <input
              type="text"
              placeholder="Search for spaces..."
              value={searchQuery}
              onChange={(e) => setSearchQuery(e.target.value)}
            />
            <FaSearch className="search-icon" />
          </div>

          {/* Filter Dropdown */}
          <div className="filter-dropdown">
            <FaFilter className="filter-icon" />
            <select
              value={filterStatus}
              onChange={(e) => setFilterStatus(e.target.value)}
            >
              <option value="All">All</option>
              <option value="Live">Live</option>
              <option value="Scheduled">Scheduled</option>
              <option value="Ended">Ended</option>
            </select>
          </div>
        </div>

        {/* Create Space Button */}
        <button
          className="create-space-button"
          onClick={() => navigate("/create-space")}
        >
          Create New Space
        </button>

        {/* Spaces List */}
        <ul className="spaces-list">
          {currentSpaces.map((space) => {
            const ended = isSpaceEnded(space);
            const scheduled = isSpaceScheduled(space);
            const now = Date.now();
            const diff = space.startedAt - now;
            const fiveMinutes = 5 * 60 * 1000;
            const canJoinNow = diff <= fiveMinutes && !ended;
            let statusIcon;
            if (ended)
              statusIcon = (
                <>
                  <FaFlagCheckered style={{ color: "#d93025" }} /> Ended
                </>
              );
            else if (scheduled)
              statusIcon = (
                <>
                  <FaClock style={{ color: "#b58f00" }} /> Scheduled
                </>
              );
            else
              statusIcon = (
                <>
                  <FaCheckCircle style={{ color: "#1da1f2" }} /> Live
                </>
              );
            const joinStatus = getJoinStatus(space, user?.id!);

            return (
              <li key={space.id} className="space-card">
                {/* Header */}
                <div className="space-card-header">
                  <h3 className="space-card-title">{space.title}</h3>
                  <span
                    className={`space-card-status ${
                      ended ? "ended" : scheduled ? "scheduled" : "live"
                    }`}
                  >
                    {statusIcon}
                  </span>
                </div>

                {/* Description */}
                <p className="space-card-description">{space.description}</p>

                {/* Meta Information */}
                <div className="space-card-meta">
                  <span className="space-card-participants">
                    <FaUsers /> {participantCount(space)} participants
                  </span>
                </div>

                {/* Actions */}
                <div className="space-actions">
                  {canJoinNow && !ended ? (
                    joinStatus === "Approved" ? (
                      <button onClick={() => navigate(`/space/${space.id}`)}>
                        Join
                      </button>
                    ) : joinStatus === "Lobby" ? (
                      <button
                        onClick={async () => {
                          await joinSpace(space.id, user!, !space.askToSpeak);
                          navigate(`/space/${space.id}`);
                        }}
                      >
                        Join
                      </button>
                    ) : joinStatus === "Request to join" ? (
                      <button
                        onClick={async () => {
                          await joinSpace(space.id, user!, !space.askToSpeak);
                          setPendingJoin((prev) => [
                            ...prev,
                            [space.id, user!.id],
                          ]);
                        }}
                      >
                        Request to join
                      </button>
                    ) : (
                      <span className="join-status">{joinStatus}</span>
                    )
                  ) : ended ? (
                    <span className="ended-label">This space has ended</span>
                  ) : scheduled ? (
                    <span className="scheduled-label">
                      Starts soon. Check back closer to start time.
                    </span>
                  ) : (
                    <button onClick={() => navigate(`/space/${space.id}`)}>
                      {!canJoinNow && "View Details"}
                    </button>
                  )}
                </div>
              </li>
            );
          })}
        </ul>
        {message && <div className="error-message">{message}</div>}

        {/* Pagination Controls */}
        {totalPages > 1 && (
          <div className="pagination-controls">
            {/* Items Per Page */}
            <div className="items-per-page">
              <FaList className="pagination-icon" />
              <label htmlFor="itemsPerPage">Show:</label>
              <select
                id="itemsPerPage"
                value={itemsPerPage}
                onChange={handleItemsPerPageChange}
              >
                <option value={5}>5</option>
                <option value={10}>10</option>
                <option value={25}>25</option>
                <option value={50}>50</option>
              </select>
            </div>

            {/* Page Navigation */}
            <div className="page-navigation">
              <button
                onClick={handleFirstPage}
                disabled={currentPage === 1}
                title="First Page"
                aria-label="First Page"
              >
                <FaAngleDoubleLeft />
              </button>
              <button
                onClick={handlePrevPage}
                disabled={currentPage === 1}
                title="Previous Page"
                aria-label="Previous Page"
              >
                <FaChevronLeft />
              </button>
              <span className="current-page">
                Page {currentPage} of {totalPages}
              </span>
              <button
                onClick={handleNextPage}
                disabled={currentPage === totalPages}
                title="Next Page"
                aria-label="Next Page"
              >
                <FaChevronRight />
              </button>
              <button
                onClick={handleLastPage}
                disabled={currentPage === totalPages}
                title="Last Page"
                aria-label="Last Page"
              >
                <FaAngleDoubleRight />
              </button>
            </div>
          </div>
        )}
      </div>

      {/* Right Sidebar - Recent Spaces */}
      <div className="right-sidebar">
        <h3>Recent Spaces</h3>
        <div className="sidebar-card-container">
          {recentSpaces.map((space) => (
            <div
              key={space.id}
              className="sidebar-card"
              onClick={() => navigate(`/space/${space.id}`)}
            >
              <h4 className="sidebar-card-title">{space.title}</h4>
              <p className="sidebar-card-participants">
                <FaUsers /> {participantCount(space)} participants
              </p>
              <p className="sidebar-card-status">
                {isSpaceEnded(space)
                  ? "Ended"
                  : isSpaceScheduled(space)
                  ? "Scheduled"
                  : "Live"}
              </p>
            </div>
          ))}
        </div>
      </div>
    </div>
  );
};
