// mediasfu_reactjs/src/components/SpaceDetails.tsx
import React, { useEffect, useState } from "react";
import { useParams, useNavigate } from "react-router-dom";
import {
  fetchSpaceById,
  joinSpace,
  leaveSpace,
  muteParticipant,
  endSpace,
  rejectRequest,
  approveRequest,
  fetchUserById,
  requestToSpeak,
  approveJoinRequest,
  rejectJoinRequest,
} from "../api";
import { Space, ParticipantData } from "../types";
import {
  FaMicrophone,
  FaMicrophoneSlash,
  FaSignOutAlt,
  FaUserSlash,
  FaCheck,
  FaTimes,
  FaArrowLeft,
  FaPowerOff,
  FaUsers,
  FaEye,
  FaCheckCircle,
  FaClock,
  FaFlagCheckered,
  FaConnectdevelop,
} from "react-icons/fa";
import Spinner from "./Spinner";
import Modal from "./Modal";
import "../styles/SpaceDetails.css";
import ParticipantCard from "./ParticipantCard";

export const SpaceDetails: React.FC = () => {
  const { spaceId } = useParams<{ spaceId: string }>();
  const navigate = useNavigate();
  const [space, setSpace] = useState<Space | undefined>();
  const [currentUser, setCurrentUser] = useState<ParticipantData | undefined>(
    undefined
  );
  const [isLoading, setIsLoading] = useState(true);
  const [canSpeak, setCanSpeak] = useState(
    currentUser !== undefined &&
      (currentUser?.role === "speaker" ||
        currentUser?.role === "host" ||
        !space?.askToSpeak)
  );
  const [showJoinRequests, setShowJoinRequests] = useState(false);
  const [showSpeakRequests, setShowSpeakRequests] = useState(false);
  const [message, setMessage] = useState("");
  const [alertedRemainingTime, setAlertedRemainingTime] = useState(false);

  // Determine if the current user has been rejected from speaking
  const hasRejectedSpeakRequest = space?.askToSpeakHistory.includes(
    currentUser?.id || ""
  );

  const [isConnected, setIsConnected] = useState(false);
  const [isMuted, setIsMuted] = useState(true);
  const [banned, setBanned] = useState<boolean>(false);

  const now = Date.now();
  const ended = space?.endedAt !== 0 || !space?.active;
  const scheduled = now < space?.startedAt!;
  const remainingTime = space?.duration
    ? space?.startedAt + space?.duration - now
    : 0;
  const totalDuration = space?.duration || 1; 
  const progress = Math.max(
    0,
    Math.min((1 - remainingTime / totalDuration) * 100, 100)
  );

  const isHost = currentUser?.id === space?.host;
  const canJoinNow =
    space?.startedAt! - now <= 5 * 60 * 1000 && space?.active && !ended;

  useEffect(() => {
    (async () => {
      const uid = localStorage.getItem("currentUserId");
      if (!uid) {
        navigate("/welcome"); 
        return;
      }

      try {
        const s = await fetchSpaceById(spaceId!);
        if (!s) {
          navigate("/"); 
          return;
        }
        setSpace(s);

        const p = s.participants.find((part) => part.id === uid);

        //canSpeak
        if (p?.role === "speaker" && !canSpeak) {
          setMessage("You have been granted speaker role.");
          setCanSpeak(true);
        }
        setCurrentUser(p);
      } catch (error) {
        console.error("Error fetching space:", error);
        navigate("/");
      } finally {
        setIsLoading(false); 
      }
    })();
  }, [spaceId, navigate, canSpeak]);

  async function loadSpace() {
    const newSpace = await fetchSpaceById(spaceId!);
    if (newSpace) {
      setSpace(newSpace);
      const currentUserId = localStorage.getItem("currentUserId");
      if (currentUserId) {
        const p = newSpace.participants.find(
          (part) => part.id === currentUserId
        );
        if (p) setCurrentUser(p);
      }
    }
  }

  useEffect(() => {
    loadSpace();
    const interval = setInterval(loadSpace, 1000); 
    return () => clearInterval(interval);
    // eslint-disable-next-line react-hooks/exhaustive-deps
  }, []);

  useEffect(() => {
    if (message) {
      setTimeout(() => {
        setMessage("");
      }, 4000);
    }
  }, [message]);

  useEffect(() => {
    if (space?.duration) {
      const now = Date.now();
      const remainingTime = space?.startedAt + space?.duration - now;
      if (remainingTime < 0) {
        setMessage("Space has ended.");
        endSpace(spaceId!);
        setTimeout(() => {
          navigate("/");
        }, 500);
      } else if (remainingTime < 60000 && !alertedRemainingTime) {
        setMessage("Space will end in less than a minute.");
        setAlertedRemainingTime(true);
      }
    }

    if (space?.endedAt && space?.endedAt !== 0) {
      setMessage("Space has ended.");
      setTimeout(() => {
        navigate("/");
      }, 500);
    }

    if (space?.banned && space?.banned.includes(currentUser?.id!)) {
      setBanned(true);
      setMessage("You have been banned from this space.");
      handleLeave();
      setTimeout(async () => {
        await leaveSpace(spaceId!, currentUser?.id!);
        navigate("/");
      }, 500);
    }
    // eslint-disable-next-line react-hooks/exhaustive-deps
  }, [navigate, space, spaceId, alertedRemainingTime, currentUser]);

  useEffect(() => {
    if (
      currentUser &&
      (currentUser.role === "speaker" ||
        currentUser.role === "host" ||
        !space?.askToSpeak) &&
      !canSpeak
    ) {
      setCanSpeak(true);
    }
  }, [currentUser, canSpeak, space]);

  if (isLoading) {
    return <Spinner />;
  }

  if (!space) {
    return <div>Space not found. Redirecting...</div>; // Fallback in case of redirection failure
  }

  async function handleJoin() {
    const currentUserId = localStorage.getItem("currentUserId");
    if (!currentUserId) return;
    const user = await fetchUserById(currentUserId);
    if (!user) return;
    if (banned || space?.banned?.includes(user.id)) {
      setMessage("You have been banned from this space.");
      return;
    }

    if (
      space?.askToJoin &&
      !(isHost || space?.approvedToJoin.includes(user.id))
    ) {
      // Handle join requests
      const existingRequest = space?.askToJoinQueue.includes(user.id);
      if (existingRequest) {
        setMessage("Your request to join is pending approval by the host.");
        return;
      } else {
        const existingHistory = space?.rejectedSpeakers.includes(user.id);
        if (existingHistory) {
          setMessage("Your request to join was rejected by the host.");
          return;
        }
      }

      await joinSpace(space?.id, user, !space?.askToSpeak);
      const updated = await fetchSpaceById(space?.id);
      if (updated) {
        setSpace(updated);
        const p = updated.participants.find(
          (part) => part.id === currentUserId
        );
        if (p) setCurrentUser(p);
        setMessage(
          "Your request to join has been sent and is pending approval."
        );
      }
    } else {
      // Directly join
      await joinSpace(space?.id!, user, !space?.askToSpeak);
      const updated = await fetchSpaceById(space?.id!);
      if (updated) {
        setSpace(updated);
        const p = updated.participants.find(
          (part) => part.id === currentUserId
        );
        if (p) setCurrentUser(p);
      }
    }
  }

  async function handleLeave() {
    if (currentUser) {
      await leaveSpace(space?.id!, currentUser.id);
      navigate("/");
    }
  }

  async function handleMuteParticipant(targetId: string) {
    await muteParticipant(space?.id!, targetId, true);
    const updated = await fetchSpaceById(space?.id!);
    if (updated) setSpace(updated);
  }

  async function handleEndSpace() {
    if (isHost) {
      await endSpace(space?.id!);
      const updated = await fetchSpaceById(space?.id!);
      if (updated) setSpace(updated);
      setTimeout(() => {
        navigate("/");
      }, 1000);
    }
  }

  async function handleRemoveParticipant(targetId: string) {
    if (isHost) {
      const updated = await fetchSpaceById(space?.id!);
      if (updated) setSpace(updated);
    }
  }

  async function handleToggleMic() {
    if (
      currentUser?.role === "speaker" ||
      currentUser?.role === "host" ||
      !space?.askToSpeak
    ) {
     
    } else {
      setMessage("You do not have permission to toggle your mic.");
    }
  }

  // Function to check speak request status
  function checkRequestToSpeak() {
    if (hasRejectedSpeakRequest) {
      setMessage("You have been rejected from speaking in this space.");
      return;
    }

    const isPending = space?.askToSpeakQueue.includes(currentUser?.id!);
    if (isPending) {
      setMessage("Your request to speak is pending approval by the host.");
      return;
    } else if (space?.rejectedSpeakers.includes(currentUser?.id!)) {
      setMessage("Your request to speak was rejected by the host.");
      return;
    }
    // If not pending and not rejected, allow to request
    requestToSpeak(space?.id!, currentUser?.id!)
      .then(() => {
        setMessage(
          "Your request to speak has been sent and is pending approval."
        );
        loadSpace();
      })
      .catch((error) => {
        setMessage("Error requesting to speak. Please try again.");
      });
  }

  // Function to manage join requests via modal
  const handleApproveJoin = async (userId: string) => {
    await approveJoinRequest(space?.id, userId, false); // Approve as listener
    loadSpace();
  };

  const handleRejectJoin = async (userId: string) => {
    await rejectJoinRequest(space?.id, userId);
    loadSpace();
  };

  // Function to manage speak requests via modal
  const handleApproveSpeak = async (userId: string) => {
    await approveRequest(space?.id, userId, true); // Approve as speaker
    loadSpace();
  };

  const handleRejectSpeak = async (userId: string) => {
    await rejectRequest(space?.id, userId);
    loadSpace();
  };

  // Function to get counts of speakers and listeners
  function getCounts(space: Space) {
    const speakers = space?.speakers.length;
    const listeners = space?.listeners.length;
    // add the host as a speaker
    if (space?.host && !space?.speakers.includes(space?.host)) {
      return { speakers: speakers + 1, listeners };
    }

    return { speakers, listeners };
  }

  const { speakers, listeners } = getCounts(space);

  return (
    <div className="space-details-container container">
      {/* Header with Back and End Space Buttons */}
      <div className="space-header">
        <button className="back-button" onClick={() => navigate("/")}>
          <FaArrowLeft className="icon" />
          Back
        </button>
        {currentUser && space?.active && !ended && (
          <div className="audio-controls">
            <div className="status-indicator">
              <div
                className={`connection-status ${
                  isConnected ? "connected" : "disconnected"
                }`}
                title={isConnected ? "Connected" : "Disconnected"}
              ></div>
            </div>

            {isConnected ? (
              canSpeak ? (
                <>
                  <div className="mic-controls">
                    <button
                      className="toggle-mic-btn"
                      onClick={handleToggleMic}
                      aria-label={isMuted ? "Turn on" : "Turn off"}
                    >
                      {isMuted ? <FaMicrophoneSlash /> : <FaMicrophone />}{" "}
                      {isMuted ? "Turn on" : "Turn off"} Mic
                    </button>
                  </div>
                </>
              ) : (
                <button
                  className="request-speak-btn"
                  onClick={checkRequestToSpeak}
                >
                  <FaMicrophoneSlash /> Request to Speak
                </button>
              )
            ) : (
              <button
                className="connect-btn"
                onClick={() => {
                  /* Not yet implemented */
                  setMessage("This feature is not yet implemented.");
                }}
              >
                <FaConnectdevelop /> Connect Audio
              </button>
            )}
            {isHost && space?.active ? (
              <button className="end-space-button" onClick={handleEndSpace}>
                <FaPowerOff className="icon" />
                End Space
              </button>
            ) : (
              <button className="leave-button" onClick={handleLeave}>
                <FaSignOutAlt /> Leave
              </button>
            )}
          </div>
        )}
        {/* Join and Speak Controls */}
        {!currentUser && space?.active && canJoinNow && !ended && (
          <button className="join-button" onClick={handleJoin}>
            <FaCheckCircle /> Join
          </button>
        )}
      </div>

      {message && <div className="error-message">{message}</div>}
      {/* Space Information */}
      <div className="space-info">
        <h2 className="space-title">{space?.title}</h2>
        <p className="space-description">{space?.description}</p>
        <div className="space-status-icons">
          {ended && (
            <div className="status-icon ended">
              <FaFlagCheckered /> Ended
            </div>
          )}
          {scheduled && !ended && (
            <div className="status-icon scheduled">
              <FaClock /> Scheduled
            </div>
          )}
          {!scheduled && space?.active && !ended && (
            <div className="status-icon live">
              <FaCheckCircle /> Live Now
            </div>
          )}
        </div>
        {/* Viewer and Listener Counts */}
        <div className="space-counts">
          <span>
            <FaUsers /> {speakers} Speakers
          </span>
          <span>
            <FaEye /> {listeners} Listeners
          </span>
        </div>
        {/* Progress Bar */}
        {space?.active && !ended && (
          <div className="progress-bar">
            <div className="progress" style={{ width: `${progress}%` }}></div>
          </div>
        )}

        {isHost && (space?.askToJoin || space?.askToSpeak) && !ended && (
          <div className="request-buttons">
            {space?.askToJoin && (
              <button
                className="manage-request-btn"
                onClick={() => setShowJoinRequests(true)}
              >
                <FaUserSlash /> Join Requests
                <span className="pill">
                  {space?.askToJoinQueue.length > 0
                    ? space?.askToJoinQueue.length
                    : ""}
                </span>
              </button>
            )}
            {space?.askToSpeak && (
              <button
                className="manage-request-btn"
                onClick={() => setShowSpeakRequests(true)}
              >
                <FaMicrophone /> Speak Requests
                <span className="pill">
                  {space?.askToSpeakQueue.length > 0
                    ? space?.askToSpeakQueue.length
                    : ""}
                </span>
              </button>
            )}
          </div>
        )}
      </div>

      {/* Join Requests Modal */}
      <Modal
        isOpen={showJoinRequests}
        onClose={() => setShowJoinRequests(false)}
        title="Join Requests"
      >
        {space?.askToJoinQueue.length === 0 ? (
          <p>No join requests.</p>
        ) : (
          space?.askToJoinQueue.map((id) => {
            const user = space?.participants.find((p) => p.id === id);
            return (
              <div key={id} className="request-card">
                <span>{user?.displayName || id}</span>
                <div>
                  <button
                    className="accept-btn"
                    onClick={() => handleApproveJoin(id)}
                    title="Approve Join"
                  >
                    <FaCheck />
                  </button>
                  <button
                    className="reject-btn"
                    onClick={() => handleRejectJoin(id)}
                    title="Reject Join"
                  >
                    <FaTimes />
                  </button>
                </div>
              </div>
            );
          })
        )}
      </Modal>

      {/* Speak Requests Modal */}
      <Modal
        isOpen={showSpeakRequests}
        onClose={() => setShowSpeakRequests(false)}
        title="Speak Requests"
      >
        {space?.askToSpeakQueue.length === 0 ? (
          <p>No speak requests.</p>
        ) : (
          space?.askToSpeakQueue.map((id) => {
            const user = space?.participants.find((p) => p.id === id);
            return (
              <div key={id} className="request-card">
                <span>{user?.displayName || id}</span>
                <div>
                  <button
                    className="accept-btn"
                    onClick={() => handleApproveSpeak(id)}
                    title="Approve Speak"
                  >
                    <FaCheck />
                  </button>
                  <button
                    className="reject-btn"
                    onClick={() => handleRejectSpeak(id)}
                    title="Reject Speak"
                  >
                    <FaTimes />
                  </button>
                </div>
              </div>
            );
          })
        )}
      </Modal>

      {/* Participant Grid */}
      <div className="participants-section">
        <h3>Participants</h3>
        <div className="participants-grid">
          {space?.participants.map((p) => {
            return (
              <ParticipantCard
                key={p.id}
                participant={p}
                isHost={isHost || false}
                currentUserId={currentUser?.id}
                onMute={(id) => {
                  handleMuteParticipant(id);
                }}
                onToggleMic={(part) => {
                  if (part.id === currentUser?.id && part.role === "speaker") {
                    handleToggleMic();
                  }
                }}
                onRemove={(id) => {
                  if (isHost) {
                    handleRemoveParticipant(id);
                  }
                }}
                space={space}
              />
            );
          })}
        </div>
      </div>

    </div>
  );
};

// mediasfu_angular/src/app/components/space-details-components/space-details.component.ts
import { Component, OnInit, OnDestroy, ChangeDetectionStrategy } from '@angular/core';
import { BehaviorSubject, Subscription, interval } from 'rxjs';
import { ActivatedRoute, Router } from '@angular/router';
import { FontAwesomeModule } from '@fortawesome/angular-fontawesome';
import { CommonModule } from '@angular/common';
import { FormsModule } from '@angular/forms';
import { ApiService } from '../../api/api.service';
import { Space, ParticipantData } from '../../../types';
import {
  faMicrophone, faMicrophoneSlash, faCrown, faSignOutAlt, faUserSlash, faCheck, faTimes, faArrowLeft, faPowerOff, faUsers, faEye,
  faCheckCircle, faClock, faFlagCheckered, faSyncAlt, faCamera, faArrowRight
} from '@fortawesome/free-solid-svg-icons';


import { ModalComponent } from '../modal-components/modal.component';
import { ParticipantCardComponent } from '../participant-card-components/participant-card.component';
import { SpinnerComponent } from '../spinner-components/spinner.component';



@Component({
  selector: 'app-space-details',
  templateUrl: './space-details.component.html',
  styleUrls: ['./space-details.component.css'],
  providers: [ApiService],
  imports: [CommonModule, FormsModule, FontAwesomeModule, ModalComponent,
    ParticipantCardComponent, SpinnerComponent],
  changeDetection: ChangeDetectionStrategy.OnPush,
})
export class SpaceDetailsComponent implements OnInit, OnDestroy {
  // FontAwesome Icons
  faMicrophone = faMicrophone;
  faMicrophoneSlash = faMicrophoneSlash;
  faCrown = faCrown;
  faSignOutAlt = faSignOutAlt;
  faUserSlash = faUserSlash;
  faCheck = faCheck;
  faTimes = faTimes;
  faArrowLeft = faArrowLeft;
  faPowerOff = faPowerOff;
  faUsers = faUsers;
  faEye = faEye;
  faCheckCircle = faCheckCircle;
  faClock = faClock;
  faFlagCheckered = faFlagCheckered;
  faSyncAlt = faSyncAlt;
  faCamera = faCamera;
  faArrowRight = faArrowRight;

  // State Management with BehaviorSubjects
  space = new BehaviorSubject<Space | null>(null);
  currentUser = new BehaviorSubject<ParticipantData | null>(null);
  message = new BehaviorSubject<string>('');
  isLoading = new BehaviorSubject<boolean>(true);
  canSpeak = new BehaviorSubject<boolean>(false);
  showJoinRequests = new BehaviorSubject<boolean>(false);
  showSpeakRequests = new BehaviorSubject<boolean>(false);
  alertedRemainingTime = new BehaviorSubject<boolean>(false);
  isMuted = new BehaviorSubject<boolean>(true);

  isConnected = new BehaviorSubject<boolean>(false);
  participants = new BehaviorSubject<ParticipantData[]>([]);

  canJoinNow = new BehaviorSubject<boolean>(false);
  banned = new BehaviorSubject<boolean>(false);

  // Additional Properties
  spaceId: string | null = null;
  refreshSub!: Subscription;


  progress = 0;
  scheduled = false;
  ended = false;
  private previousSpace: Space | null = null;
  private isFetching = false; // Prevent overlapping API calls

  constructor(
    private route: ActivatedRoute,
    public router: Router,
    private apiService: ApiService,
  ) { }

  ngOnInit(): void {
    // Retrieve spaceId from route parameters
    this.spaceId = this.route.snapshot.paramMap.get('spaceId');

    // Initial data load
    this.loadSpace(this.spaceId!);

    // Set up interval to refresh space every second
    this.refreshSub = interval(1000).subscribe(() => {
      this.loadSpace(this.spaceId!);
    });
  }

  ngOnDestroy(): void {
    if (this.refreshSub) {
      this.refreshSub.unsubscribe();
    }
    // Additional cleanup if necessary
  }

  /**
   * Loads space data and updates state accordingly.
   */
  private async loadSpace(spaceId: string): Promise<void> {
    if (this.isFetching) return; // Prevent overlapping calls
    this.isFetching = true;

    const uid = localStorage.getItem('currentUserId');
    if (!uid) {
      this.router.navigate(['/welcome']);
      return;
    }

    try {
      const newSpace = await this.apiService.fetchSpaceById(spaceId);
      if (!newSpace) {
        this.router.navigate(['/']);
        return;
      }

      // Update state only if the data has changed
      if (JSON.stringify(this.previousSpace) !== JSON.stringify(newSpace)) {
        this.previousSpace = newSpace;
        this.space.next(newSpace);
        this.participants.next(newSpace.participants);

        this.space?.next(newSpace);

        const p = newSpace.participants.find(part => part.id === uid) || null;
        this.currentUser.next(p);


        // Update canSpeak status
        if (p?.role === 'speaker' || p?.role === 'host' || !newSpace.askToSpeak) {
          this.canSpeak.next(true);
        } else {
          this.canSpeak.next(false);
        }

        // Update loading state
        this.isLoading.next(false);

        // Handle space state changes (e.g., ended, scheduled)
        this.handleSpaceState(newSpace);
      }

      this.updateDerivedState(newSpace);
    } catch (error) {
      console.error('Error loading space:', error);
      this.message.next('Failed to load space. Please try again later.');
    } finally {
      this.isFetching = false;
    }
  }

  /**
   * Updates derived state like progress, scheduled, ended, and canJoinNow.
   */
  private updateDerivedState(space: Space): void {
    const now = Date.now();
    this.scheduled = now < space.startedAt;
    this.ended = !!space.endedAt && !space.active;

    const remainingTime = space.startedAt + (space.duration || 0) - now;
    const totalDuration = space.duration || 1;
    this.progress = Math.max(0, Math.min((1 - remainingTime / totalDuration) * 100, 100));

    this.canJoinNow.next(remainingTime <= 5 * 60 * 1000 && !this.ended);
  }

  /**
   * Handles joining a space?.
   */
  async handleJoin(): Promise<void> {
    const currentUserId = localStorage.getItem('currentUserId');
    if (!currentUserId) return;

    try {
      const user = await this.apiService.fetchUserById(currentUserId);
      if (!user) return;

      const currentSpace = this.space?.value;
      if (!currentSpace) return;

      if (currentSpace.askToJoin && !(currentSpace.host === currentUserId || currentSpace.approvedToJoin.includes(user.id))) {
        const existingRequest = currentSpace.askToJoinQueue.includes(user.id);
        if (existingRequest) {
          this.message.next('Your request to join is pending approval by the host.');
          return;
        } else {
          const existingHistory = currentSpace.askToJoinHistory.includes(user.id);
          if (existingHistory) {
            this.message.next('Your request to join was rejected by the host.');
            return;
          }
        }

        await this.apiService.joinSpace(currentSpace.id, user, !currentSpace.askToSpeak);
        const updatedSpace = await this.apiService.fetchSpaceById(currentSpace.id);
        if (updatedSpace) {
          this.space?.next(updatedSpace);
          const p = updatedSpace.participants.find(part => part.id === currentUserId) || null;
          this.currentUser.next(p);
          this.message.next('Your request to join has been sent and is pending approval.');
        }
      } else {
        // Directly join
        await this.apiService.joinSpace(currentSpace.id, user, !currentSpace.askToSpeak);
        const updatedSpace = await this.apiService.fetchSpaceById(currentSpace.id);
        if (updatedSpace) {
          this.space?.next(updatedSpace);
          const p = updatedSpace.participants.find(part => part.id === currentUserId) || null;
          this.currentUser.next(p);
        }
      }
    } catch (error) {
      console.error('Error joining space:', error);
    }
  }

  /**
   * Handles leaving a space?.
   */
  async handleLeave(): Promise<void> {
    const currentSpace = this.space?.value;
    const user = this.currentUser.value;
    if (currentSpace && user) {
      try {
        await this.apiService.leaveSpace(currentSpace.id, user.id);
        this.router.navigate(['/']);
      } catch (error) {
        console.error('Error leaving space:', error);
      }
    }
  }

  /**
   * Handles muting a participant.
   * @param targetId Participant ID to mute.
   */
  async handleMuteParticipant(targetId: string): Promise<void> {
    const currentSpace = this.space?.value;
    if (currentSpace) {
      try {
        await this.apiService.muteParticipant(currentSpace.id, targetId, true);
        const updatedSpace = await this.apiService.fetchSpaceById(currentSpace.id);
        if (updatedSpace) {
          this.space?.next(updatedSpace);
        }
      } catch (error) {
        console.error('Error muting participant:', error);
      }
    }
  }

  async handleRemoveParticipant(targetId: string): Promise<void> {
    const currentSpace = this.space?.value;
    if (currentSpace) {
      try {
        const updatedSpace = await this.apiService.fetchSpaceById(currentSpace.id);
        if (updatedSpace) {
          this.space?.next(updatedSpace);
        }
      } catch (error) {
        console.error('Error removing participant:', error);
      }
    }
  }

  /**
   * Handles ending the space (host only).
   */
  async handleEndSpace(): Promise<void> {
    const currentSpace = this.space?.value;
    if (currentSpace && this.isHost()) {
      try {
        await this.apiService.endSpace(currentSpace.id);
        this.space?.next(currentSpace);
        setTimeout(() => {
          this.router.navigate(['/']);
        }, 1000);
      } catch (error) {
        console.error('Error ending space:', error);
      }
    }
  }

  /**
   * Toggles the microphone.
   */
  async handleToggleMic(): Promise<void> {
    const user = this.currentUser.value;
    const space = this.space?.value;
    if (user && space) {
      if (user.role === 'speaker' || user.role === 'host' || !space?.askToSpeak) {
        try {
        } catch (error) {
          console.error('Error toggling mic:', error);
        }
      } else {
        this.message.next('You do not have permission to toggle your mic.');
      }
    }
  }

  /**
   * Requests to speak.
   */
  async checkRequestToSpeak(): Promise<void> {
    const space = this.space?.value;
    const user = this.currentUser.value;
    if (!space || !user) return;

    const hasRejectedSpeakRequest = space?.rejectedSpeakers.includes(user.id);
    if (hasRejectedSpeakRequest) {
      this.message.next('You have been rejected from speaking in this space?.');
      return;
    }

    const isPending = space?.askToSpeakQueue.includes(user.id);
    if (isPending) {
      this.message.next('Your request to speak is pending approval by the host.');
      return;
    } else if (space?.rejectedSpeakers.includes(user.id)) {
      this.message.next('Your request to speak has been rejected by the host.');
      return;
    }

    try {
      await this.apiService.requestToSpeak(space?.id, user.id);
      this.message.next('Your request to speak has been sent and is pending approval.');
      this.loadSpace(space?.id);
    } catch (error) {
      this.message.next('Error requesting to speak. Please try again.');
    }
  }

  /**
   * Approves a join request.
   * @param userId User ID to approve.
   */
  async handleApproveJoin(userId: string): Promise<void> {
    const space = this.space?.value;
    if (space) {
      try {
        await this.apiService.approveJoinRequest(space?.id, userId, false);
        this.loadSpace(space?.id);
      } catch (error) {
        console.error('Error approving join request:', error);
      }
    }
  }

  /**
   * Rejects a join request.
   * @param userId User ID to reject.
   */
  async handleRejectJoin(userId: string): Promise<void> {
    const space = this.space?.value;
    if (space) {
      try {
        await this.apiService.rejectJoinRequest(space?.id, userId);
        this.loadSpace(space?.id);
      } catch (error) {
        console.error('Error rejecting join request:', error);
      }
    }
  }

  /**
   * Approves a speak request.
   * @param userId User ID to approve.
   */
  async handleApproveSpeak(userId: string): Promise<void> {
    const space = this.space?.value;
    if (space) {
      try {
        await this.apiService.approveRequest(space?.id, userId, true);
        this.loadSpace(space?.id);
      } catch (error) {
        console.error('Error approving speak request:', error);
      }
    }
  }

  /**
   * Rejects a speak request.
   * @param userId User ID to reject.
   */
  async handleRejectSpeak(userId: string): Promise<void> {
    const space = this.space?.value;
    if (space) {
      try {
        await this.apiService.rejectRequest(space?.id, userId);
        this.loadSpace(space?.id);
      } catch (error) {
        console.error('Error rejecting speak request:', error);
      }
    }
  }

  /**
   * Retrieves counts of speakers and listeners.
   * @param space Current space data.
   */
  getCounts(space: Space): { speakers: number, listeners: number } {
    let speakers = space?.speakers.length;
    let listeners = space?.listeners.length;

    if (space?.host && !space?.speakers.includes(space?.host)) {
      speakers += 1;
    }

    return { speakers, listeners };
  }

  /**
   * Checks if the current user is the host.
   */
  isHost(): boolean {
    const currentUser = this.currentUser.value;
    const space = this.space?.value;
    return currentUser?.id === space?.host;
  }

  /**
   * Handles space state changes like ending or scheduling.
   * @param space Current space data.
   */
  async handleSpaceState(space: Space): Promise<void> {
    const now = Date.now();
    const ended = space?.endedAt !== 0 || !space?.active;
    const scheduled = now < space?.startedAt;
    const remainingTime = space?.duration ? space?.startedAt + space?.duration - now : 0;
    const totalDuration = space?.duration || 1;
    const progress = Math.max(0, Math.min((1 - remainingTime / totalDuration) * 100, 100));
    this.progress = progress;
    this.scheduled = scheduled;
    this.ended = ended;
    if (!this.canJoinNow.value) this.canJoinNow.next(this.getCanJoinNow(space));

    if (space?.duration) {
      if (remainingTime < 0) {
        this.message.next('Space has ended.');
        await this.apiService.endSpace(space?.id);
        setTimeout(() => {
          this.router.navigate(['/']);
        }, 500);
      } else if (remainingTime < 60000 && !this.alertedRemainingTime.value) {
        this.message.next('Space will end in less than a minute.');
        this.alertedRemainingTime.next(true);
      }
    }

    if (space?.endedAt && space?.endedAt !== 0) {
      this.message.next('Space has ended.');
      setTimeout(() => {
        this.router.navigate(['/']);
      }, 500);
    }

    //banned users
    if (space?.banned?.includes(this.currentUser.value?.id ?? localStorage.getItem('currentUserId')!)) {
      this.banned.next(true);
      this.message.next('You have been banned from this space.');
      await this.apiService.leaveSpace(space?.id, this.currentUser.value?.id!);
      setTimeout(() => {
        this.router.navigate(['/']);
      }, 500);
    }
  }

  /**
   * Retrieves the display name of a participant by ID.
   * @param id Participant ID.
   */
  getParticipantDisplayName(id: string): string {
    const space = this.space?.value;
    if (space) {
      const participant = space?.participants.find(p => p.id === id);
      return participant ? participant.displayName : id;
    }
    return id;
  }

  /**
 * Determines if a space has ended.
 * @param space The space to evaluate.
 */
  isSpaceEnded(space: Space): boolean {
    return !!space?.endedAt && !space?.active;
  }

  /**
 * Determines if a space can be joined now.
 * @param space The space to evaluate.
 */
  getCanJoinNow(space: Space): boolean {
    const diff = space?.startedAt - Date.now();
    const fiveMinutes = 5 * 60 * 1000;
    const ended = this.isSpaceEnded(space);
    return diff <= fiveMinutes && !ended;
  }

  /**
  * Tracks participants by their ID to minimize re-renders.
  */
  trackByParticipantId(index: number, participant: ParticipantData): string {
    return participant.id;
  }

}

<div class="space-details-container container">
  <!-- Header with Back and End Space Buttons -->
  <div class="space-header">
    <button class="back-button" (click)="router.navigate(['/'])">
      <fa-icon [icon]="faArrowLeft" class="icon"></fa-icon>
      Back
    </button>

    <!-- Audio Controls Section -->
    <!-- If the user is in the space, the space is active, and there's no endedAt date yet -->
    <div
      *ngIf="
        (currentUser | async) &&
        (space | async)?.active &&
        !(space | async)?.endedAt
      "
      class="audio-controls"
    >
      <div class="status-indicator">
        <div
          class="connection-status"
          [ngClass]="{
            connected: (isConnected | async),
            disconnected: !(isConnected | async)
          }"
          [title]="(isConnected | async) ? 'Connected' : 'Disconnected'"
        ></div>
      </div>

      <!-- If connected to the audio system -->
      <ng-container *ngIf="isConnected | async; else connectButton">
        <!-- If current user can speak -->
        <ng-container *ngIf="canSpeak | async; else requestSpeakButton">
          <div class="mic-controls">
            <button
              class="toggle-mic-btn"
              (click)="handleToggleMic()"
              [attr.aria-label]="(isMuted | async) ? 'Turn on' : 'Turn off'"
            >
              <fa-icon
                [icon]="(isMuted | async) ? faMicrophoneSlash : faMicrophone"
              ></fa-icon>
              {{ (isMuted | async) ? "Turn on" : "Turn off" }} Mic
            </button>
          </div>
        </ng-container>

        <!-- If the user can't speak, show the "Request to Speak" button -->
        <ng-template #requestSpeakButton>
          <button class="request-speak-btn" (click)="checkRequestToSpeak()">
            <fa-icon [icon]="faMicrophoneSlash"></fa-icon> Request to Speak
          </button>
        </ng-template>
      </ng-container>

      <!-- If not connected, show the "Connect Audio" button -->
      <ng-template #connectButton>
        <button class="connect-btn">
          <fa-icon [icon]="faArrowRight"></fa-icon> Connect Audio
        </button>
      </ng-template>

      <!-- Host actions -->
      <ng-container *ngIf="isHost() && (space | async)?.active">
        <button class="end-space-button" (click)="handleEndSpace()">
          <fa-icon [icon]="faPowerOff" class="icon"></fa-icon>
          End Space
        </button>
      </ng-container>

      <!-- Non-host or inactive space: "Leave" button -->
      <ng-container *ngIf="!isHost() || !(space | async)?.active">
        <button class="leave-button" (click)="handleLeave()">
          <fa-icon [icon]="faSignOutAlt"></fa-icon> Leave
        </button>
      </ng-container>
    </div>

    <!-- Join and Speak Controls -->
    <!-- If user is not in the space, space is active, and canJoinNow is true, and space is not ended -->
    <ng-container
      *ngIf="
        !(currentUser | async) &&
        (space | async)?.active &&
        canJoinNow &&
        !ended
      "
    >
      <button class="join-button" (click)="handleJoin()">
        <fa-icon [icon]="faCheckCircle"></fa-icon> Join
      </button>
    </ng-container>
  </div>

  <!-- Message -->
  <div *ngIf="message | async" class="error-message">
    {{ message | async }}
  </div>

  <!-- Space Information -->
  <div class="space-info">
    <h2 class="space-title">{{ (space | async)?.title }}</h2>
    <p class="space-description">{{ (space | async)?.description }}</p>

    <!-- Status Icons -->
    <div class="space-status-icons">
      <div *ngIf="ended" class="status-icon ended">
        <fa-icon [icon]="faFlagCheckered"></fa-icon> Ended
      </div>
      <div
        *ngIf="scheduled && !(space | async)?.endedAt"
        class="status-icon scheduled"
      >
        <fa-icon [icon]="faClock"></fa-icon> Scheduled
      </div>
      <div
        *ngIf="
          !scheduled && (space | async)?.active && !(space | async)?.endedAt
        "
        class="status-icon live"
      >
        <fa-icon [icon]="faCheckCircle"></fa-icon> Live Now
      </div>
    </div>

    <!-- Speakers & Listeners Count -->
    <div class="space-counts">
      <span>
        <fa-icon [icon]="faUsers"></fa-icon>
        {{ getCounts((space | async)!).speakers }} Speakers
      </span>
      <span>
        <fa-icon [icon]="faEye"></fa-icon>
        {{ getCounts((space | async)!).listeners }} Listeners
      </span>
    </div>

    <!-- Progress Bar if space is active and not ended -->
    <div
      *ngIf="(space | async)?.active && !(space | async)?.endedAt"
      class="progress-bar"
    >
      <div class="progress" [style.width.%]="progress"></div>
    </div>

    <!-- Request Buttons -->
    <div
      *ngIf="
        isHost() &&
        ((space | async)?.askToJoin || (space | async)?.askToSpeak) &&
        !(space | async)?.endedAt
      "
      class="request-buttons"
    >
      <button class="manage-request-btn" (click)="showJoinRequests.next(true)">
        <fa-icon [icon]="faUserSlash"></fa-icon> Join Requests
        <span
          class="pill"
          *ngIf="((space | async)?.askToJoinQueue)!.length > 0"
        >
          {{ ((space | async)?.askToJoinQueue)!.length }}
        </span>
      </button>
      <button class="manage-request-btn" (click)="showSpeakRequests.next(true)">
        <fa-icon [icon]="faMicrophone"></fa-icon> Speak Requests
        <span
          class="pill"
          *ngIf="((space | async)?.askToSpeakQueue)!.length > 0"
        >
          {{ ((space | async)?.askToSpeakQueue)!.length }}
        </span>
      </button>
    </div>
  </div>

  <!-- Join Requests Modal -->
  <app-modal
    [isOpen]="(showJoinRequests | async) ?? false"
    (onClose)="showJoinRequests.next(false)"
    title="Join Requests"
  >
    <ng-container *ngIf="((space | async)?.askToJoinQueue)!.length === 0">
      <p>No join requests.</p>
    </ng-container>
    <ng-container *ngIf="((space | async)?.askToJoinQueue)!.length > 0">
      <div
        *ngFor="let id of (space | async)?.askToJoinQueue"
        class="request-card"
      >
        <span>{{ getParticipantDisplayName(id) }}</span>
        <div>
          <button
            class="accept-btn"
            (click)="handleApproveJoin(id)"
            title="Approve Join"
          >
            <fa-icon [icon]="faCheck"></fa-icon>
          </button>
          <button
            class="reject-btn"
            (click)="handleRejectJoin(id)"
            title="Reject Join"
          >
            <fa-icon [icon]="faTimes"></fa-icon>
          </button>
        </div>
      </div>
    </ng-container>
  </app-modal>

  <!-- Speak Requests Modal -->
  <app-modal
    [isOpen]="(showSpeakRequests | async) ?? false"
    (onClose)="showSpeakRequests.next(false)"
    title="Speak Requests"
  >
    <ng-container *ngIf="((space | async)?.askToSpeakQueue)!.length === 0">
      <p>No speak requests.</p>
    </ng-container>
    <ng-container *ngIf="((space | async)?.askToSpeakQueue)!.length > 0">
      <div
        *ngFor="let id of (space | async)?.askToSpeakQueue"
        class="request-card"
      >
        <span>{{ getParticipantDisplayName(id) }}</span>
        <div>
          <button
            class="accept-btn"
            (click)="handleApproveSpeak(id)"
            title="Approve Speak"
          >
            <fa-icon [icon]="faCheck"></fa-icon>
          </button>
          <button
            class="reject-btn"
            (click)="handleRejectSpeak(id)"
            title="Reject Speak"
          >
            <fa-icon [icon]="faTimes"></fa-icon>
          </button>
        </div>
      </div>
    </ng-container>
  </app-modal>

  <!-- Participant Grid -->
  <div class="participants-section">
    <h3>Participants</h3>
    <div class="participants-grid">
      <app-participant-card
        *ngFor="
          let p of (space | async)?.participants;
          trackBy: trackByParticipantId
        "
        [participant]="p"
        [isHost]="isHost()"
        [currentUserId]="(currentUser | async)?.id"
        (onMute)="handleMuteParticipant($event)"
        (onToggleMic)="handleToggleMic()"
        (onRemoveParticipant)="handleRemoveParticipant($event)"
        [space]="(space | async)!"
      >
      </app-participant-card>
    </div>
  </div>

  <!-- Loading Spinner -->
  <app-spinner *ngIf="isLoading | async"></app-spinner>
</div>
